import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Knowledge Base',
      items: [{type: 'autogenerated', dirName: 'knowledge-base'}],
    },
    {
      type: 'category',
      label: 'Governance',
      items: [
        'PROJECT_CONTEXT',
        'PROJECT_CONSTITUTION',
        'SITE_ARCHITECTURE',
        'EDITORIAL_GUIDE',
        'AI_OPERATING_MANUAL',
        'SOURCE_AUTHORITY',
        'RESEARCH_METHODOLOGY',
        'CONTENT_BLUEPRINT',
        'MASTER_CONTENT_PLAN',
        'CONTENT_INDEX',
        'CLAIM_CLASSIFICATION',
        'ARTICLE_SPECIFICATION',
        'SCRIPTURE_INDEX',
      ],
    },
  ],
};

export default sidebars;
